sudo: required

services:
  - docker

before_install: 
  - docker build -t rahadiansetya/docker-react -f Dockerfile.dev .

script: 
  - docker run rahadiansetya/docker-react npm run test -- --coverage